#!/bin/sh

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 2 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-06_00-26-40' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_00-46-16' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_01-02-04' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_01-20-19' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_01-38-13' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_01-58-05' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-11-58' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-22-10' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-28-16' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-35-05' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-42-01' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-48-39' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_02-55-29' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-03-49' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-11-27' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-18-51' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-26-26' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-33-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-40-28' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-48-09' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_03-55-04' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-02-09' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-08-39' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-15-00' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-20-53' 	

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-28-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-35-10' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-42-06' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-48-31' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-54-54' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-01-48' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-08-56' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-15-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-22-56' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-29-14' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-36-50' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-43-46' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-50-53' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-57-39' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-04-22' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-10-51' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-17-20' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-24-42' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-31-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-37-20' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-43-59' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-50-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-57-54' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-04-44' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-11-27' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-18-43' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-25-55' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-32-21' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-38-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-45-32' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-52-29' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-58-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-05-58' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-13-07' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-19-29' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-26-42' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-33-58' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-41-17' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-49-06' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-55-59' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-02-33' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-09-07' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-52-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-59-54' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-08-18' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-17-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-25-00' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-33-26' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-41-35' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-49-59' 