#!/bin/sh

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-28-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-35-10' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-42-06' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-48-31' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_04-54-54' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-01-48' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-08-56' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-15-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-57-39' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-04-22' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-36-50' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-43-46' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_05-50-53' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-30-30' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-36-43' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-10-51' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-17-20' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-24-42' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-31-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-37-20' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-43-59' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-50-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_06-57-54' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-04-44' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-11-27' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc none  -tstcc_tm train_linear -tstcc_dir '22-10-06_04-28-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_04-35-10' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_04-42-06' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_04-48-31' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_04-54-54' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-01-48' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-08-56' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-15-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-57-39' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_06-04-22' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-36-50' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-43-46' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_05-50-53' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-30-30' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-36-43' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-10-51' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-17-20' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-24-42' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-31-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-37-20' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-43-59' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-50-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_06-57-54' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_07-04-44' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_07-11-27' 
