#!/bin/sh
python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-01-18' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-08-16' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-14-35' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-21-59' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-29-37' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-35-54' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-42-31' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-48-46' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_01-56-20' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-03-30' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-10-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-16-32' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-23-20' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-30-30' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-36-43' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-43-32' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-50-04' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_02-57-02' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-04-10' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-11-27' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-18-14' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-25-22' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-32-21' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-38-42' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-04_03-45-02' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc none  -tstcc_tm train_linear -tstcc_dir '22-10-04_01-01-18' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-04_01-08-16' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-04_01-14-35' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-04_01-21-59' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-04_01-29-37' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-04_01-35-54' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-04_01-42-31' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-04_01-48-46' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-04_01-56-20' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-03-30' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-10-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-16-32' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-23-20' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-30-30' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-04_02-36-43' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_02-43-32' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_02-50-04' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_02-57-02' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-04-10' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-11-27' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-18-14' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-25-22' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-32-21' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-38-42' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 3 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-04_03-45-02' 