#!/bin/sh
python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-18-43' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-25-55' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-32-21' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-38-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-45-32' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-52-29' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_07-58-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-05-58' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-13-07' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-19-29' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-26-42' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-33-58' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-41-17' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-49-06' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-06_08-55-59' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-02-33' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-09-07' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-52-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_09-59-54' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-08-18' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-17-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-25-00' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-33-26' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-41-35' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-06_10-49-59' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc none  -tstcc_tm train_linear -tstcc_dir '22-10-06_07-18-43' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_07-25-55' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_07-32-21' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_07-38-23' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-06_07-45-32' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_07-52-29' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_07-58-49' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-05-58' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-13-07' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-19-29' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-26-42' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-33-58' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-41-17' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-49-06' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-06_08-55-59' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_09-02-33' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_09-09-07' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_09-52-37' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_09-59-54' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-08-18' 

python3 main.py -c configs/config_c_f.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-17-02' 
python3 main.py -c configs/config_c_all.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-25-00' 
python3 main.py -c configs/config_c_a.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-33-26' 
python3 main.py -c configs/config_c_b.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-41-35' 
python3 main.py -c configs/config_c_c.json -exp ts_tcc -n_clusters 4 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-06_10-49-59' 