#!/bin/sh
python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none  -tstcc_tm fine_tune -tstcc_dir '22-10-11_12-43-24' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-11_13-07-54' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-11_13-26-54' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-11_13-48-01' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm fine_tune -tstcc_dir '22-10-11_14-06-25' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_14-25-29' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_14-40-02' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_14-57-40' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_15-11-10' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_15-26-28' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_15-41-12' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_15-54-44' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_16-10-50' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_16-26-51' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm fine_tune -tstcc_dir '22-10-11_16-42-34' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_16-59-25' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_17-14-45' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_17-30-05' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_17-45-34' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_18-01-08' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_18-16-08' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_18-31-29' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_18-45-13' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_19-00-53' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm fine_tune -tstcc_dir '22-10-11_19-16-56' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none  -tstcc_tm train_linear -tstcc_dir '22-10-11_12-43-24' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-11_13-07-54' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-11_13-26-54' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-11_13-48-01' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc none -tstcc_tm train_linear -tstcc_dir '22-10-11_14-06-25' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-11_14-25-29' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-11_14-40-02' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-11_14-57-40' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-11_15-11-10' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc absolute_days -tstcc_tm train_linear -tstcc_dir '22-10-11_15-26-28' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-11_15-41-12' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-11_15-54-44' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-11_16-10-50' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-11_16-26-51' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc delta_days -tstcc_tm train_linear -tstcc_dir '22-10-11_16-42-34' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_16-59-25' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_17-14-45' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_17-30-05' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_17-45-34' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc age_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_18-01-08' 

python3 main.py -c configs/config_c_f_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_18-16-08' 
python3 main.py -c configs/config_c_all_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_18-31-29' 
python3 main.py -c configs/config_c_a_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_18-45-13' 
python3 main.py -c configs/config_c_b_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_19-00-53' 
python3 main.py -c configs/config_c_c_bal.json -exp ts_tcc -n_clusters 2 -pos_enc learnable_pos_enc -tstcc_tm train_linear -tstcc_dir '22-10-11_19-16-56' 
